name: telegram-action
description: "Envía un mensaje de confirmación del workflow al usuario."
inputs:
  telegram_token:
    description: "Token del usuario de Telegram"
    required: true
  telegram_id_user:
    description: "Id del usuario de Telegram"
    required: true
outputs:
  msg:
    description: "Mensaje de respuesta del script"
runs:
  using: "node20"
  main: "index.js"
