name: pruebadespliegue_workflow

# se ejecutará al hacer push en la rama main
on:
  push:
    branches:
      - main

jobs:
  # ejecución del Linter_job para comprobar la sintaxis del código
  Linter_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Establecer versión de Node
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Instalación de dependencias
      - name: Install dependencies
        run: npm install

      # Step 4: Linter execution
      - name: Linter execution
        run: npm run lint
  Cypress_job:
    runs-on: ubuntu-24.04
    needs: Linter_job

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Establecer versión de Node
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Step 4: Cypress run
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          config-file: cypress.json
        continue-on-error: true
        id: cypress

      # Step 5: Creación del artefacto con el resultado del test
      - name: Crear artefacto result.txt
        run: echo ${{ steps.cypress.outcome }} > result.txt

      # Step 6: Upload artefacto
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: result.txt
          name: result.txt

  Add_badge_job:
    runs-on: ubuntu-latest
    needs: Cypress_job

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Obtener artefacto del job anterior
      - name: Descargar artefacto result.txt
        uses: actions/download-artifact@v4
        with:
          path: result.txt
          name: result.txt

      # Step 3: Test descarga del artefacto
      - name: Test artifact download
        run: ls -R

      # Step 4: Instalar dependencias
      - name: Install dependencies
        run: cd ./.github/actions/badges && npm install

      # Step 6: Generar output
      - name: Generar output
        uses: ./.github/actions/badges
        with:
          resultado: "probando 2"

      # Step 7: Commit and Push Changes
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "Santi"
          message: "Actualizado el README file"
          push: true
          token: ${{ secrets.TOKEN }}

  Deploy_job:
    runs-on: ubuntu-latest
    needs: Add_badge_job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install & build
        run: npm install && npm run build

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-blog
          path: build/

      - name: Get Artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-blog
      - name: Deploy Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./sub-directory
