name: pruebadespliegue_workflow

# se ejecutará al hacer push en la rama main
on:
  push:
    branches:
      - main

jobs:
  # ejecución del Linter_job para comprobar la sintaxis del código
  Linter_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Establecer versión de Node
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Instalación de dependencias
      - name: Install dependencies
        run: npm install

      # Step 4: Linter execution
      - name: Linter execution
        run: npm run lint
  Cypress_job:
    runs-on: ubuntu-24.04
    needs: Linter_job
    strategy:
      matrix:
        node: [18, 20, 22]

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Establecer versiones de Node
      - name: Setup node versions
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      # Step 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Step 4: Cypress run
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          config-file: cypress.json
        continue-on-error: true
        id: cypress
      - name: Crear artefacto result.txt
        uses: actions/upload-artifact@v4
        with:
          path: .
          name: result.txt
  Add_badge_job:
    runs-on: ubuntu-latest
    needs: Cypress_job

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Obtener artefacto del job anterior
      - name: Descargar artefacto result.txt
        uses: actions/download-artifact@v3
        with:
          name: result.txt

      - name: Test artifact download
        run: ls -R

      # Step 3: Generar output
